print ("python is working")
print ("python is working")
print ("python is working")
print ("python is working")
print ("python is working")
print ("python is working")
print ("python is working")
print ("python is working")
print ("python is working")
print ("python is working")

